/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author juanm
 */
public class AparatosPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    public AparatosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apaTitle = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tipoLabel = new javax.swing.JLabel();
        nsLabeel = new javax.swing.JLabel();
        macLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        contratoLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        lasDlabel = new javax.swing.JLabel();
        obserPanel = new javax.swing.JLabel();
        obervaText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        actualDlbale = new javax.swing.JLabel();
        listaDiag = new javax.swing.JScrollPane();
        actualDiag = new javax.swing.JList<>();
        diagnoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        apaTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        apaTitle.setText("Diagnóstico de aparatos");

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchButton.setText("Buscar");

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tipoLabel.setText("Tipo de aparato:");

        nsLabeel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nsLabeel.setText("N/S:");

        macLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        macLabel.setText("MAC:");

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nombreLabel.setText("NOMBRE");

        contratoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contratoLabel.setText("Contrato:");

        estadoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estadoLabel.setText("Estado general:");

        lasDlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lasDlabel.setText("Último diagnóstico:");

        obserPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        obserPanel.setText("Observaciones:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        obervaText.setViewportView(jTextArea1);

        actualDlbale.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        actualDlbale.setText("Diagnóstico actual:");

        actualDiag.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaDiag.setViewportView(actualDiag);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nsLabeel)
                                    .addComponent(tipoLabel)
                                    .addComponent(contratoLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(macLabel)
                                    .addComponent(nombreLabel)
                                    .addComponent(estadoLabel))
                                .addGap(268, 268, 268))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(lasDlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obserPanel)
                            .addComponent(obervaText, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actualDlbale)
                    .addComponent(listaDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoLabel)
                            .addComponent(nombreLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nsLabeel)
                            .addComponent(macLabel))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoLabel)
                            .addComponent(contratoLabel))
                        .addGap(18, 18, 18)
                        .addComponent(lasDlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obserPanel)
                        .addGap(18, 18, 18)
                        .addComponent(obervaText, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(actualDlbale)
                        .addGap(18, 18, 18)
                        .addComponent(listaDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        diagnoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        diagnoButton.setText("Ejecutar diagnóstico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(448, 448, 448)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(apaTitle))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diagnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(595, 595, 595))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(apaTitle)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(diagnoButton)
                .addGap(0, 7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> actualDiag;
    private javax.swing.JLabel actualDlbale;
    private javax.swing.JLabel apaTitle;
    private javax.swing.JLabel contratoLabel;
    private javax.swing.JButton diagnoButton;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lasDlabel;
    private javax.swing.JScrollPane listaDiag;
    private javax.swing.JLabel macLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nsLabeel;
    private javax.swing.JScrollPane obervaText;
    private javax.swing.JLabel obserPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel tipoLabel;
    // End of variables declaration//GEN-END:variables
}
