/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author juanm
 */
public class EstadisPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    public EstadisPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inciPanel = new javax.swing.JPanel();
        incidenciasTable = new javax.swing.JScrollPane();
        inciTabla = new javax.swing.JTable();
        listadoText = new javax.swing.JLabel();
        inciTitle = new javax.swing.JLabel();
        estaTitle = new javax.swing.JLabel();
        panelRecuento = new javax.swing.JPanel();
        totalResueltas = new javax.swing.JLabel();
        totalSinco = new javax.swing.JLabel();
        totalPendientes2 = new javax.swing.JLabel();
        pendTItle = new javax.swing.JLabel();
        resTitle1 = new javax.swing.JLabel();
        sinTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        inciPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inciTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        incidenciasTable.setViewportView(inciTabla);

        listadoText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        listadoText.setText("Listado de Incidencias");

        javax.swing.GroupLayout inciPanelLayout = new javax.swing.GroupLayout(inciPanel);
        inciPanel.setLayout(inciPanelLayout);
        inciPanelLayout.setHorizontalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listadoText))
            .addComponent(incidenciasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        inciPanelLayout.setVerticalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inciPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listadoText)
                .addGap(18, 18, 18)
                .addComponent(incidenciasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inciTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        inciTitle.setText("Estadísticas de incidencias");

        estaTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        estaTitle.setText("Estadísticas por día");

        panelRecuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        totalResueltas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalResueltas.setText("0");

        totalSinco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalSinco.setText("0");

        totalPendientes2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalPendientes2.setText("0");

        pendTItle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pendTItle.setText("Pendientes");

        resTitle1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        resTitle1.setText("Resueltas");

        sinTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sinTitle.setText("Sin Comunicar");

        javax.swing.GroupLayout panelRecuentoLayout = new javax.swing.GroupLayout(panelRecuento);
        panelRecuento.setLayout(panelRecuentoLayout);
        panelRecuentoLayout.setHorizontalGroup(
            panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pendTItle)
                .addGap(180, 180, 180)
                .addComponent(resTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(sinTitle)
                .addGap(25, 25, 25))
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(totalPendientes2)
                .addGap(330, 330, 330)
                .addComponent(totalResueltas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalSinco)
                .addGap(120, 120, 120))
        );
        panelRecuentoLayout.setVerticalGroup(
            panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendTItle)
                    .addComponent(sinTitle)
                    .addComponent(resTitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalResueltas)
                    .addComponent(totalSinco)
                    .addComponent(totalPendientes2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(inciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estaTitle)
                .addGap(0, 290, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(panelRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(inciTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(inciTitle)
                .addGap(36, 36, 36)
                .addComponent(panelRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(inciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(estaTitle)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel estaTitle;
    private javax.swing.JPanel inciPanel;
    private javax.swing.JTable inciTabla;
    private javax.swing.JLabel inciTitle;
    private javax.swing.JScrollPane incidenciasTable;
    private javax.swing.JLabel listadoText;
    private javax.swing.JPanel panelRecuento;
    private javax.swing.JLabel pendTItle;
    private javax.swing.JLabel resTitle1;
    private javax.swing.JLabel sinTitle;
    private javax.swing.JLabel totalPendientes2;
    private javax.swing.JLabel totalResueltas;
    private javax.swing.JLabel totalSinco;
    // End of variables declaration//GEN-END:variables
}
