/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.jmmunoz.netfix.utilities;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author juanm
 */
public class EstadisPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    public EstadisPanel() {

        initComponents();
        cargarDatos();

    }

    public void cargarDatos() {
        SwingUtilities.invokeLater(() -> {
            try {
                utilities ut = new utilities();
                ResultSet rs = ut.ejecutarConsulta(utilities.TipoConsulta.INCIDENCIAS, 0);
                ut.cargarTabla(inciTabla, rs);
                ut.cargarGrafico(grafiPanel);

                int[] contadores = ut.obtenerContadorIncidencias();
                //System.out.println(contadores[0] + " " + contadores[1] + " " + contadores[2]);
                totalPendientes.setText(String.valueOf(contadores[0]));
                totalResueltas.setText(String.valueOf(contadores[1]));
                totalSinco.setText(String.valueOf(contadores[2]));
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inciPanel = new javax.swing.JPanel();
        incidenciasTable = new javax.swing.JScrollPane();
        inciTabla = new javax.swing.JTable();
        listadoText = new javax.swing.JLabel();
        inciTitle = new javax.swing.JLabel();
        panelRecuento = new javax.swing.JPanel();
        totalResueltas = new javax.swing.JLabel();
        totalSinco = new javax.swing.JLabel();
        totalPendientes = new javax.swing.JLabel();
        pendTItle = new javax.swing.JLabel();
        resTitle1 = new javax.swing.JLabel();
        sinTitle = new javax.swing.JLabel();
        grafiPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        inciPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inciTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        incidenciasTable.setViewportView(inciTabla);

        listadoText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        listadoText.setText("Listado de Incidencias");

        javax.swing.GroupLayout inciPanelLayout = new javax.swing.GroupLayout(inciPanel);
        inciPanel.setLayout(inciPanelLayout);
        inciPanelLayout.setHorizontalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(listadoText))
            .addComponent(incidenciasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        inciPanelLayout.setVerticalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inciPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(listadoText)
                .addGap(18, 18, 18)
                .addComponent(incidenciasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        inciTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        inciTitle.setText("Estadísticas de incidencias");

        panelRecuento.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        totalResueltas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalResueltas.setText("0");

        totalSinco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalSinco.setText("0");

        totalPendientes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalPendientes.setText("0");

        pendTItle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        pendTItle.setText("Pendientes");

        resTitle1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        resTitle1.setText("Resueltas");

        sinTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sinTitle.setText("Sin Comunicar");

        javax.swing.GroupLayout panelRecuentoLayout = new javax.swing.GroupLayout(panelRecuento);
        panelRecuento.setLayout(panelRecuentoLayout);
        panelRecuentoLayout.setHorizontalGroup(
            panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pendTItle)
                .addGap(180, 180, 180)
                .addComponent(resTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(sinTitle)
                .addGap(25, 25, 25))
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(totalPendientes)
                .addGap(330, 330, 330)
                .addComponent(totalResueltas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalSinco)
                .addGap(120, 120, 120))
        );
        panelRecuentoLayout.setVerticalGroup(
            panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecuentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pendTItle)
                    .addComponent(sinTitle)
                    .addComponent(resTitle1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRecuentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalResueltas)
                    .addComponent(totalSinco)
                    .addComponent(totalPendientes))
                .addContainerGap())
        );

        javax.swing.GroupLayout grafiPanelLayout = new javax.swing.GroupLayout(grafiPanel);
        grafiPanel.setLayout(grafiPanelLayout);
        grafiPanelLayout.setHorizontalGroup(
            grafiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );
        grafiPanelLayout.setVerticalGroup(
            grafiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(inciPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grafiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(inciTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(panelRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(inciTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRecuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grafiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grafiPanel;
    private javax.swing.JPanel inciPanel;
    private javax.swing.JTable inciTabla;
    private javax.swing.JLabel inciTitle;
    private javax.swing.JScrollPane incidenciasTable;
    private javax.swing.JLabel listadoText;
    private javax.swing.JPanel panelRecuento;
    private javax.swing.JLabel pendTItle;
    private javax.swing.JLabel resTitle1;
    private javax.swing.JLabel sinTitle;
    private javax.swing.JLabel totalPendientes;
    private javax.swing.JLabel totalResueltas;
    private javax.swing.JLabel totalSinco;
    // End of variables declaration//GEN-END:variables
}
