/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author juanm
 */
public class IncidPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    public IncidPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inciPanel = new javax.swing.JPanel();
        listadoText = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        incidenciasTable = new javax.swing.JScrollPane();
        inciTabla = new javax.swing.JTable();
        inciGTitle = new javax.swing.JLabel();
        datosPanel = new javax.swing.JPanel();
        gestiPanel = new javax.swing.JLabel();
        sepaDatos = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        comenTable = new javax.swing.JTable();
        comenLabel = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        contatoLabel = new javax.swing.JLabel();
        problemaLabel = new javax.swing.JLabel();
        sepaAparatos = new javax.swing.JSeparator();
        tituLabel = new javax.swing.JLabel();
        ftthLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        movilLabel = new javax.swing.JLabel();
        soluButton = new javax.swing.JButton();
        actuButton = new javax.swing.JButton();
        enviButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        inciPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        listadoText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        listadoText.setText("Listado de Incidencias");

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchButton.setText("Buscar");

        inciTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        incidenciasTable.setViewportView(inciTabla);

        javax.swing.GroupLayout inciPanelLayout = new javax.swing.GroupLayout(inciPanel);
        inciPanel.setLayout(inciPanelLayout);
        inciPanelLayout.setHorizontalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inciPanelLayout.createSequentialGroup()
                        .addComponent(listadoText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(inciPanelLayout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addComponent(incidenciasTable)
        );
        inciPanelLayout.setVerticalGroup(
            inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inciPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(listadoText)
                .addGap(18, 18, 18)
                .addComponent(incidenciasTable, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        inciGTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        inciGTitle.setText("Gestión de incidencias");

        datosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        gestiPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gestiPanel.setText("INCIDENCIA EN GESTIÓN");

        comenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(comenTable);

        comenLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        comenLabel.setText("Comentarios");

        numLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        numLabel.setText("Nº");

        contatoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contatoLabel.setText("Contrato:");

        problemaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        problemaLabel.setText("Problema:");

        tituLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituLabel.setText("Titular:");
        tituLabel.setToolTipText("");

        ftthLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ftthLabel.setText("FTTH:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        movilLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        movilLabel.setText("Móvil:");

        soluButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        soluButton.setText("Solucionar");

        actuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        actuButton.setText("Actualizar");

        enviButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        enviButton.setText("Enviar Técnico");

        javax.swing.GroupLayout datosPanelLayout = new javax.swing.GroupLayout(datosPanel);
        datosPanel.setLayout(datosPanelLayout);
        datosPanelLayout.setHorizontalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sepaDatos)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(datosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(datosPanelLayout.createSequentialGroup()
                        .addComponent(gestiPanel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(numLabel)
                        .addGap(221, 221, 221))
                    .addGroup(datosPanelLayout.createSequentialGroup()
                        .addComponent(comenLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sepaAparatos, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, datosPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(datosPanelLayout.createSequentialGroup()
                        .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(datosPanelLayout.createSequentialGroup()
                                .addComponent(soluButton)
                                .addGap(217, 217, 217)
                                .addComponent(actuButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(enviButton))
                            .addGroup(datosPanelLayout.createSequentialGroup()
                                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(datosPanelLayout.createSequentialGroup()
                                        .addComponent(contatoLabel)
                                        .addGap(144, 144, 144)
                                        .addComponent(tituLabel))
                                    .addComponent(problemaLabel)
                                    .addComponent(ftthLabel)
                                    .addComponent(movilLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        datosPanelLayout.setVerticalGroup(
            datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gestiPanel)
                    .addComponent(numLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contatoLabel)
                    .addComponent(tituLabel))
                .addGap(30, 30, 30)
                .addComponent(problemaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepaAparatos, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(ftthLabel)
                .addGap(57, 57, 57)
                .addComponent(movilLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(datosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soluButton)
                    .addComponent(actuButton)
                    .addComponent(enviButton))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(537, 537, 537)
                .addComponent(inciGTitle)
                .addGap(0, 584, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inciGTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actuButton;
    private javax.swing.JLabel comenLabel;
    private javax.swing.JTable comenTable;
    private javax.swing.JLabel contatoLabel;
    private javax.swing.JPanel datosPanel;
    private javax.swing.JButton enviButton;
    private javax.swing.JLabel ftthLabel;
    private javax.swing.JLabel gestiPanel;
    private javax.swing.JLabel inciGTitle;
    private javax.swing.JPanel inciPanel;
    private javax.swing.JTable inciTabla;
    private javax.swing.JScrollPane incidenciasTable;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel listadoText;
    private javax.swing.JLabel movilLabel;
    private javax.swing.JLabel numLabel;
    private javax.swing.JLabel problemaLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JSeparator sepaAparatos;
    private javax.swing.JSeparator sepaDatos;
    private javax.swing.JButton soluButton;
    private javax.swing.JLabel tituLabel;
    // End of variables declaration//GEN-END:variables
}
