/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.jmmunoz.netfix.Usuario;
import com.jmmunoz.netfix.utilities;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.Insets;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;

/**
 *
 * @author juanm
 */
public class login extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    utilities ut;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        ut = new utilities();
        if (!java.beans.Beans.isDesignTime()) {
            initUIPro();  // solo en ejecución
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JPasswordField();
        mailUser = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        iniciarText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        password.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        password.setToolTipText("Ingrese su contraseña");

        mailUser.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mailUser.setToolTipText("Ingrese su usuario");

        loginButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        loginButton.setText("Acceder");
        loginButton.setToolTipText("Clic para acceder");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        iniciarText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        iniciarText.setText("Bienvenido al sistema Netfix");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniciarText, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mailUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iniciarText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mailUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String email = mailUser.getText().trim();
        String pass = new String(password.getPassword()).trim();

        // 1️⃣ Campos vacíos
        if (email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Email y contraseña son obligatorios",
                    "Campos vacíos",
                    JOptionPane.WARNING_MESSAGE
            );
            return; // ⛔ no continúa
        }

        // 2️⃣ Email no válido
        if (!ut.checkEmail(email)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Solo se permiten correos @netfix.com o @netfix.es",
                    "Dominio no permitido",
                    JOptionPane.WARNING_MESSAGE
            );
            mailUser.requestFocus();
            return; // ⛔ no continúa
        }

        // 3️⃣ Login
        boolean acceso = ut.loggin(email, pass);

        if (!acceso) {
            JOptionPane.showMessageDialog(
                    this,
                    "Usuario o contraseña incorrectos",
                    "Error de acceso",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 4️⃣ Acceso correcto → cargar usuario
        try {
            ResultSet rs = ut.ejecutarConsulta(
                    utilities.TipoConsulta.USUARIO,
                    email
            );

            if (rs.next()) {

                Usuario usuario = new Usuario(
                        rs.getString("id_usuario"),
                        rs.getString("nombre"),
                        rs.getString("rol"),
                        rs.getString("email"),
                        rs.getString("password")
                );

                mainFrame mf = new mainFrame(usuario);
                mf.setVisible(true);
                this.dispose();
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error al acceder a la base de datos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void initUIPro() {

        setTitle("NETFIX | Acceso");
        setMinimumSize(new Dimension(560, 420));
        setLocationRelativeTo(null);

        /* =========================
       ROOT (FONDO)
       ========================= */
        JPanel root = new JPanel(new GridBagLayout());
        root.setBorder(new EmptyBorder(12, 12, 12, 12));
        root.putClientProperty(
                FlatClientProperties.STYLE,
                "background: #F5F6F8;"
        );

        /* =========================
       CARD CENTRAL
       ========================= */
        JPanel card = new JPanel();
        card.setLayout(new BoxLayout(card, BoxLayout.Y_AXIS));
        card.setBorder(new CompoundBorder(
                new LineBorder(new Color(220, 224, 230), 1, true),
                new EmptyBorder(20, 20, 20, 20)
        ));
        card.putClientProperty(
                FlatClientProperties.STYLE,
                "background: #FFFFFF;"
        );
        card.setMaximumSize(new Dimension(600, Integer.MAX_VALUE));

        /* =========================
       LOGO
       ========================= */
        JLabel logoLabel = new JLabel();
        logoLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

        URL logoUrl = getClass().getResource("/img/netfix_logo.png");
        URL logoIcon = getClass().getResource("/img/netfix_N.png");
        if (logoUrl != null) {
            ImageIcon icon = new ImageIcon(logoUrl);
            Image scaled = icon.getImage()
                    .getScaledInstance(300, -1, Image.SCALE_SMOOTH);
            logoLabel.setIcon(new ImageIcon(scaled));
        } else {
            logoLabel.setText("NETFIX");
            logoLabel.setFont(new Font("Segoe UI", Font.BOLD, 28));
        }

        /* =========================
       BADGE
       ========================= */
        JLabel badge = new JLabel("NOC · TICKETS · SLA");
        badge.setOpaque(true);
        badge.setAlignmentX(Component.CENTER_ALIGNMENT);
        badge.putClientProperty(
                FlatClientProperties.STYLE,
                "background: #EEF4FF; foreground: #2E90FA; arc: 999; "
                + "border: 6,12,6,12; font: bold 12 'Segoe UI';"
        );

        /* =========================
       SUBTÍTULO
       ========================= */
        JLabel subtitle = new JLabel(
                "Diagnóstico y gestión de tickets · Telecomunicaciones"
        );
        subtitle.setAlignmentX(Component.CENTER_ALIGNMENT);
        subtitle.putClientProperty(
                FlatClientProperties.STYLE,
                "font: plain 14 'Segoe UI'; foreground: #667085;"
        );

        /* =========================
       HEADER
       ========================= */
        card.add(logoLabel);
        card.add(Box.createVerticalStrut(10));
        card.add(badge);
        card.add(Box.createVerticalStrut(8));
        card.add(subtitle);
        card.add(Box.createVerticalStrut(22));

        /* =========================
       CAMPOS
       ========================= */
        mailUser.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        password.setFont(new Font("Segoe UI", Font.PLAIN, 16));

        mailUser.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));
        password.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));

        mailUser.putClientProperty(
                FlatClientProperties.PLACEHOLDER_TEXT,
                "usuario@netfix.com / usuario@netfix.es"
        );
        password.putClientProperty(
                FlatClientProperties.PLACEHOLDER_TEXT,
                "Introduce tu contraseña"
        );

        loginButton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        loginButton.setMaximumSize(new Dimension(Integer.MAX_VALUE, 42));
        loginButton.putClientProperty(
                FlatClientProperties.STYLE,
                "arc: 12;"
        );

        getRootPane().setDefaultButton(loginButton);

        card.add(fullWidth(mailUser));
        card.add(Box.createVerticalStrut(14));
        card.add(fullWidth(password));
        card.add(Box.createVerticalStrut(18));
        card.add(fullWidth(loginButton));

        /* =========================
       FOOTER
       ========================= */
        JLabel footer = new JLabel("Soporte: NOC / Sistemas · NETFIX");
        footer.setAlignmentX(Component.CENTER_ALIGNMENT);
        footer.putClientProperty(
                FlatClientProperties.STYLE,
                "font: 12 'Segoe UI'; foreground: #98A2B3;"
        );

        card.add(Box.createVerticalStrut(14));
        card.add(footer);

        /* =========================
       COLOCAR CARD
       ========================= */
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;

        root.add(card, gbc);
        setContentPane(root);

        /* =========================
       ICONO DE VENTANA
       ========================= */
        if (logoIcon != null) {
            Image base = new ImageIcon(logoIcon).getImage();

            List<Image> icons = List.of(
                    base.getScaledInstance(16, 16, Image.SCALE_SMOOTH),
                    base.getScaledInstance(24, 24, Image.SCALE_SMOOTH),
                    base.getScaledInstance(32, 32, Image.SCALE_SMOOTH),
                    base.getScaledInstance(48, 48, Image.SCALE_SMOOTH),
                    base.getScaledInstance(64, 64, Image.SCALE_SMOOTH),
                    base.getScaledInstance(128, 128, Image.SCALE_SMOOTH)
            );

            setIconImages(icons);
        }

        pack();
        SwingUtilities.invokeLater(() -> mailUser.requestFocusInWindow());
    }

    private JPanel fullWidth(Component c) {
        JPanel p = new JPanel(new BorderLayout());
        p.setOpaque(false);
        p.add(c, BorderLayout.CENTER);
        return p;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set FlatLaf (Material / Google style) look and feel */
        try {
            FlatLightLaf.setup();

            // Opcional: ajustes estilo Material
            UIManager.put("Button.arc", 999);
            UIManager.put("Component.arc", 12);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("ScrollBar.width", 12);
            UIManager.put("Component.focusColor", new Color(46, 144, 250));
            UIManager.put("Component.focusedBorderColor", new Color(46, 144, 250));
            UIManager.put("Button.focusedBorderColor", new Color(46, 144, 250));

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iniciarText;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField mailUser;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
