/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.UIManager;
import vista.EstadisPanel;

/**
 *
 * @author juanm
 */
public class mainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());
    private CardLayout cardLayout;
    private EstadisPanel estadisPanel;
    private IncidPanel incidenciasPanel;
    private AparatosPanel aparatosPanel;
    private UsuariosPanel usuariosPanel;
    private AdminPanel adminPanel;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);

        estadisPanel = new EstadisPanel();
        incidenciasPanel = new IncidPanel();
        aparatosPanel = new AparatosPanel();
        adminPanel = new AdminPanel();
        usuariosPanel = new UsuariosPanel();
        cardLayout.show(contentPanel, "estadisticas");
        contentPanel.add(estadisPanel, "estadisticas");
        contentPanel.add(incidenciasPanel, "incidencias");
        contentPanel.add(aparatosPanel, "aparatos");
        contentPanel.add(usuariosPanel, "usuarios");
        contentPanel.add(adminPanel, "admin");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        estaButon = new javax.swing.JButton();
        inciButton = new javax.swing.JButton();
        aparaButton = new javax.swing.JButton();
        usuButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelLateral.setForeground(new java.awt.Color(153, 153, 153));

        estaButon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estaButon.setText("Estadísticas");
        estaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaButonActionPerformed(evt);
            }
        });

        inciButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inciButton.setText("Incidencias");
        inciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inciButtonActionPerformed(evt);
            }
        });

        aparaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aparaButton.setText("Aparatos");
        aparaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparaButtonActionPerformed(evt);
            }
        });

        usuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuButton.setText("Usuarios");
        usuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuButtonActionPerformed(evt);
            }
        });

        adminButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        adminButton.setText("Administrar");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estaButon, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
            .addComponent(inciButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aparaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addComponent(estaButon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aparaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 698, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1567, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fondoPanelLayout = new javax.swing.GroupLayout(fondoPanel);
        fondoPanel.setLayout(fondoPanelLayout);
        fondoPanelLayout.setHorizontalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        fondoPanelLayout.setVerticalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void estaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaButonActionPerformed
        cardLayout.show(contentPanel, "estadisticas");
    }//GEN-LAST:event_estaButonActionPerformed

    private void inciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inciButtonActionPerformed
        cardLayout.show(contentPanel, "incidencias");
    }//GEN-LAST:event_inciButtonActionPerformed

    private void aparaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparaButtonActionPerformed
        cardLayout.show(contentPanel, "aparatos");
    }//GEN-LAST:event_aparaButtonActionPerformed

    private void usuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuButtonActionPerformed
        cardLayout.show(contentPanel, "usuarios");
    }//GEN-LAST:event_usuButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        cardLayout.show(contentPanel, "admin");
    }//GEN-LAST:event_adminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set FlatLaf (Material / Google style) look and feel */
        try {
            FlatLightLaf.setup();

            // Opcional: ajustes estilo Material
            UIManager.put("Button.arc", 999);
            UIManager.put("Component.arc", 12);
            UIManager.put("TextComponent.arc", 10);
            UIManager.put("ScrollBar.width", 12);

        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton aparaButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton estaButon;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JButton inciButton;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JButton usuButton;
    // End of variables declaration//GEN-END:variables
}
