/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import com.jmmunoz.netfix.Usuario;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author juanm
 */
public class mainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());
    private final CardLayout cardLayout;
    private final EstadisPanel estadisPanel;
    private final IncidPanel incidenciasPanel;
    private final AparatosPanel aparatosPanel;
    private final SupervisorPanel supervisorPanel;
    private final AdminPanel adminPanel;
    private final UsuariosPanel usuariosPanel;
    private Usuario usuario;
    private JButton activeButton = null;

    private final Color ACTIVE_BG = new Color(224, 234, 255); // azul claro NETFIX
    private final Color HOVER_BG = new Color(230, 235, 245);

    /**
     * Creates new form mainFrame
     */
    public mainFrame(Usuario usuario) {
        initComponents();
        /* =========================
       ICONO DE VENTANA
       ========================= */
        URL logoIcon = getClass().getResource("/img/netfix_N.png");
        if (logoIcon != null) {
            Image base = new ImageIcon(logoIcon).getImage();

            List<Image> icons = List.of(
                    base.getScaledInstance(16, 16, Image.SCALE_SMOOTH),
                    base.getScaledInstance(24, 24, Image.SCALE_SMOOTH),
                    base.getScaledInstance(32, 32, Image.SCALE_SMOOTH),
                    base.getScaledInstance(48, 48, Image.SCALE_SMOOTH),
                    base.getScaledInstance(64, 64, Image.SCALE_SMOOTH),
                    base.getScaledInstance(128, 128, Image.SCALE_SMOOTH)
            );

            setIconImages(icons);
        }
        this.usuario = usuario;
        cargarDatosUsuario();
        aplicarPermisosPorRol();
        setLocationRelativeTo(null);
        setActiveButton(estaButton);
        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);

        estadisPanel = new EstadisPanel();
        incidenciasPanel = new IncidPanel();
        aparatosPanel = new AparatosPanel();
        adminPanel = new AdminPanel();
        supervisorPanel = new SupervisorPanel();
        usuariosPanel = new UsuariosPanel(usuario);
        contentPanel.add(estadisPanel, "estadisticas");
        contentPanel.add(incidenciasPanel, "incidencias");
        contentPanel.add(aparatosPanel, "aparatos");
        contentPanel.add(supervisorPanel, "supervisores");
        contentPanel.add(usuariosPanel, "usuarios");
        contentPanel.add(adminPanel, "admin");
        cardLayout.show(contentPanel, "estadisticas");
        contentPanel.revalidate();
        contentPanel.repaint();

        applyHoverEffect(estaButton);
        applyHoverEffect(inciButton);
        applyHoverEffect(aparaButton);
        applyHoverEffect(usuButton);
        applyHoverEffect(adminButton);
    }

    private void cargarDatosUsuario() {
        logName.setText(usuario.getNombre());
        logRol.setText(usuario.getRol());
    }

    private void aplicarPermisosPorRol() {

        String rol = usuario.getRol().toLowerCase();

        switch (rol) {

            case "sistemas":
                // Acceso total
                adminButton.setEnabled(true);
                break;

            case "supervisor":
                // Puede ver admin pero no tocar todo (ejemplo)
                adminButton.setEnabled(false);
                // Si quieres limitar algo más, aquí
                break;

            case "tecnico":
                // Sin acceso a administración
                adminButton.setEnabled(false);
                usuButton.setText("Usuario");
                // Opcional: ocultar
                // adminButton.setVisible(false);
                break;

            default:
                // Rol desconocido = acceso mínimo
                adminButton.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        panelLateral = new javax.swing.JPanel();
        estaButton = estaButton = new javax.swing.JButton();
        estaButton.setLayout(new java.awt.BorderLayout());

        estaButton.setText("Estadísticas");
        estaButton.setFocusPainted(false);
        estaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        estaButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        estaButton.setBorderPainted(false);
        estaButton.setContentAreaFilled(false);
        estaButton.setMargin(new java.awt.Insets(10, 16, 10, 16));

        // Cargar icono
        java.net.URL estaUrl = getClass().getResource("/img/nav/stats.png");
        if (estaUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(estaUrl);
            java.awt.Image scaled = icon.getImage()
            .getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);

            javax.swing.JLabel iconLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaled));
            iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 6));
            estaButton.add(iconLabel, java.awt.BorderLayout.EAST);
        };
        inciButton = inciButton = new javax.swing.JButton();
        inciButton.setLayout(new java.awt.BorderLayout());

        inciButton.setText("Incidencias");
        inciButton.setFocusPainted(false);
        inciButton.setBorderPainted(false);
        inciButton.setContentAreaFilled(false);
        inciButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inciButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inciButton.setMargin(new java.awt.Insets(10, 16, 10, 16));

        java.net.URL inciUrl = getClass().getResource("/img/nav/incidencias.png");
        if (inciUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(inciUrl);
            java.awt.Image scaled = icon.getImage()
            .getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel iconLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaled));
            iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 6));
            inciButton.add(iconLabel, java.awt.BorderLayout.EAST);
        }
        ;
        aparaButton = aparaButton = new javax.swing.JButton();
        aparaButton.setLayout(new java.awt.BorderLayout());

        aparaButton.setText("Aparatos");
        aparaButton.setFocusPainted(false);
        aparaButton.setBorderPainted(false);
        aparaButton.setContentAreaFilled(false);
        aparaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aparaButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aparaButton.setMargin(new java.awt.Insets(10, 16, 10, 16));

        java.net.URL apaUrl = getClass().getResource("/img/nav/aparatos.png");
        if (apaUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(apaUrl);
            java.awt.Image scaled = icon.getImage()
            .getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel iconLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaled));
            iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 6));
            aparaButton.add(iconLabel, java.awt.BorderLayout.EAST);
        }
        ;
        usuButton = usuButton = new javax.swing.JButton();
        usuButton.setLayout(new java.awt.BorderLayout());

        usuButton.setText("Usuarios");
        usuButton.setFocusPainted(false);
        usuButton.setBorderPainted(false);
        usuButton.setContentAreaFilled(false);
        usuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuButton.setMargin(new java.awt.Insets(10, 16, 10, 16));

        java.net.URL userUrl = getClass().getResource("/img/nav/usuarios.png");
        if (userUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(userUrl);
            java.awt.Image scaled = icon.getImage()
            .getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel iconLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaled));
            iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 6));
            usuButton.add(iconLabel, java.awt.BorderLayout.EAST);
        }
        ;
        adminButton = adminButton = new javax.swing.JButton();
        adminButton.setLayout(new java.awt.BorderLayout());

        adminButton.setText(" Administrar");
        adminButton.setFocusPainted(false);
        adminButton.setBorderPainted(false);
        adminButton.setContentAreaFilled(false);
        adminButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        adminButton.setMargin(new java.awt.Insets(10, 16, 10, 16));

        java.net.URL adminUrl = getClass().getResource("/img/nav/admin.png");
        if (adminUrl != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(adminUrl);
            java.awt.Image scaled = icon.getImage()
            .getScaledInstance(18, 18, java.awt.Image.SCALE_SMOOTH);
            javax.swing.JLabel iconLabel = new javax.swing.JLabel(new javax.swing.ImageIcon(scaled));
            iconLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 6));
            adminButton.add(iconLabel, java.awt.BorderLayout.EAST);
        };
        logName = new javax.swing.JLabel();
        logRol = new javax.swing.JLabel();
        salir = salir = new javax.swing.JButton();

        salir.setText("");
        salir.setFocusPainted(false);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setToolTipText("Cerrar sesión");

        java.net.URL normalUrl = getClass().getResource("/img/logout.png");
        java.net.URL hoverUrl  = getClass().getResource("/img/logout_hover.png");

        javax.swing.SwingUtilities.invokeLater(() -> {

            if (normalUrl != null) {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(normalUrl);
                int size = Math.min(salir.getWidth(), salir.getHeight());
                if (size > 0) {
                    java.awt.Image scaled = icon.getImage()
                    .getScaledInstance(size, size, java.awt.Image.SCALE_SMOOTH);
                    salir.setIcon(new javax.swing.ImageIcon(scaled));
                }
            }
        });

        // Hover effect
        salir.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (hoverUrl != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(hoverUrl);
                    int size = Math.min(salir.getWidth(), salir.getHeight());
                    java.awt.Image scaled = icon.getImage()
                    .getScaledInstance(size, size, java.awt.Image.SCALE_SMOOTH);
                    salir.setIcon(new javax.swing.ImageIcon(scaled));
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (normalUrl != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(normalUrl);
                    int size = Math.min(salir.getWidth(), salir.getHeight());
                    java.awt.Image scaled = icon.getImage()
                    .getScaledInstance(size, size, java.awt.Image.SCALE_SMOOTH);
                    salir.setIcon(new javax.swing.ImageIcon(scaled));
                }
            }
        });
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));

        panelLateral.setForeground(new java.awt.Color(153, 153, 153));

        estaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        estaButton.setText(" Estadísticas");
        estaButton.setBorder(null);
        estaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estaButtonActionPerformed(evt);
            }
        });

        inciButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inciButton.setText(" Incidencias");
        inciButton.setBorder(null);
        inciButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inciButtonActionPerformed(evt);
            }
        });

        aparaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        aparaButton.setText(" Aparatos");
        aparaButton.setBorder(null);
        aparaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparaButtonActionPerformed(evt);
            }
        });

        usuButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usuButton.setText(" Usuarios");
        usuButton.setBorder(null);
        usuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuButtonActionPerformed(evt);
            }
        });

        adminButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        adminButton.setText(" Administrar");
        adminButton.setBorder(null);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        logName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        logRol.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        salir.setToolTipText("Pulse para cerrar sesión.");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inciButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aparaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(usuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addComponent(estaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inciButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aparaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLateralLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logRol, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout fondoPanelLayout = new javax.swing.GroupLayout(fondoPanel);
        fondoPanel.setLayout(fondoPanelLayout);
        fondoPanelLayout.setHorizontalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoPanelLayout.createSequentialGroup()
                .addComponent(panelLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fondoPanelLayout.setVerticalGroup(
            fondoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void estaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estaButtonActionPerformed
        setActiveButton(estaButton);
        estadisPanel.cargarDatos();
        cardLayout.show(contentPanel, "estadisticas");
    }//GEN-LAST:event_estaButtonActionPerformed

    private void inciButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inciButtonActionPerformed
        setActiveButton(inciButton);
        incidenciasPanel.cargarDatos();
        cardLayout.show(contentPanel, "incidencias");
    }//GEN-LAST:event_inciButtonActionPerformed

    private void aparaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparaButtonActionPerformed
        setActiveButton(aparaButton);
        cardLayout.show(contentPanel, "aparatos");
    }//GEN-LAST:event_aparaButtonActionPerformed

    private void usuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuButtonActionPerformed
        setActiveButton(usuButton);
        String rol = usuario.getRol().toLowerCase();

        switch (rol) {

            case "sistemas":
                // Acceso total
                cardLayout.show(contentPanel, "supervisores");
                break;

            case "supervisor":
                // Puede ver admin pero no tocar todo (ejemplo)
                cardLayout.show(contentPanel, "supervisores");
                // Si quieres limitar algo más, aquí
                break;

            case "tecnico":
                // Sin acceso a administración
                cardLayout.show(contentPanel, "usuarios");
                break;

            default:
                // Rol desconocido = acceso mínimo
                cardLayout.show(contentPanel, "usuarios");
                break;
        }


    }//GEN-LAST:event_usuButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        setActiveButton(adminButton);
        cardLayout.show(contentPanel, "admin");
    }//GEN-LAST:event_adminButtonActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas cerrar la sesión?",
                "Cerrar sesión",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            new login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_salirActionPerformed
    private void applyHoverEffect(JButton button) {

        Color hoverBg = new Color(230, 235, 245);

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                if (button != activeButton) {
                    button.setContentAreaFilled(true); // 🔥 clave
                    button.setOpaque(true);
                    button.setBackground(hoverBg);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                if (button != activeButton) {
                    button.setBackground(null);
                    button.setOpaque(false);
                    button.setContentAreaFilled(false); // 🔥 volver a tu estilo plano
                }
            }
        });

        // 🔥 Muy importante: aplicar el mismo hover a los hijos (iconLabel)
        for (java.awt.Component c : button.getComponents()) {
            c.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    if (button != activeButton) {
                        button.setContentAreaFilled(true);
                        button.setOpaque(true);
                        button.setBackground(hoverBg);
                    }
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    if (button != activeButton) {
                        button.setBackground(null);
                        button.setOpaque(false);
                        button.setContentAreaFilled(false);
                    }
                }
            });
        }
    }

    private void setActiveButton(JButton button) {

        // Desactivar el anterior
        if (activeButton != null) {
            activeButton.setBackground(null);
            activeButton.setOpaque(false);
            activeButton.setFont(activeButton.getFont().deriveFont(Font.PLAIN));
        }

        // Activar el nuevo
        activeButton = button;
        activeButton.setOpaque(true);
        activeButton.setBackground(ACTIVE_BG);
        activeButton.setFont(activeButton.getFont().deriveFont(Font.BOLD));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton aparaButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton estaButton;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JButton inciButton;
    private javax.swing.JLabel logName;
    private javax.swing.JLabel logRol;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JButton salir;
    private javax.swing.JButton usuButton;
    // End of variables declaration//GEN-END:variables
}
