/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.jmmunoz.netfix.utilities;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author juanm
 */
public class SupervisorPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    private TableRowSorter<DefaultTableModel> sorter;
    ResultSet rs;
    ResultSet crs;
    utilities ut = new utilities();
    int usuario = 2;
    String usuName = "pruebas";

    public SupervisorPanel() {
        initComponents();
        cargarDatos();
    }

    public void cargarDatos() {
        crs = ut.ejecutarConsulta(utilities.TipoConsulta.ROLES, 0);
        try {
            while (crs.next()) {
                rolAlta.addItem(crs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            System.getLogger(SupervisorPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        SwingUtilities.invokeLater(() -> {
            try {
                rs = ut.ejecutarConsulta(utilities.TipoConsulta.USUARIOS, 0);
                ut.cargarTabla(usersTable, rs);

                usersTable.getSelectionModel().addListSelectionListener(e -> {
                    if (!e.getValueIsAdjusting()) {
                        int fila = usersTable.getSelectedRow();
                        if (fila != -1) {
                            idText.setText(usersTable.getValueAt(fila, 0).toString());
                            nameText.setText(usersTable.getValueAt(fila, 1).toString());
                            rs = ut.ejecutarConsulta(utilities.TipoConsulta.ROLES, 0);
                            rolCombo.removeAllItems();
                            try {
                                while (rs.next()) {
                                    rolCombo.addItem(rs.getString("descripcion"));
                                }
                            } catch (SQLException ex) {
                                System.getLogger(SupervisorPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                            }
                            rolCombo.setSelectedItem(usersTable.getValueAt(fila, 2).toString());
                            mailText.setText(usersTable.getValueAt(fila, 3).toString());
                            passText.setText(usersTable.getValueAt(fila, 4).toString());
                        }
                    }
                });
                // Actualizamos el sorter con el nuevo modelo en caso de recarga
                //sorter.setModel((DefaultTableModel) usersTable.getModel());

            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersPanel = new javax.swing.JPanel();
        ususTitle = new javax.swing.JLabel();
        searchField1 = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        mainPanel1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        emaiLabel = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();
        contratoLabel1 = new javax.swing.JLabel();
        altasTitle = new javax.swing.JLabel();
        userLlabel = new javax.swing.JLabel();
        modButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        altaLabel = new javax.swing.JLabel();
        nameAlta = new javax.swing.JTextField();
        rLabel = new javax.swing.JLabel();
        rolAlta = new javax.swing.JComboBox<>();
        maiLabel = new javax.swing.JLabel();
        mailAlta = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passAlta = new javax.swing.JPasswordField();
        confiLabel = new javax.swing.JLabel();
        confAlta = new javax.swing.JPasswordField();
        altaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        nameText = new javax.swing.JTextField();
        mailText = new javax.swing.JTextField();
        rolCombo = new javax.swing.JComboBox<>();
        passText = new javax.swing.JPasswordField();
        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        usersPanel.setBackground(new java.awt.Color(255, 255, 255));
        usersPanel.setPreferredSize(new java.awt.Dimension(1592, 946));

        ususTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        ususTitle.setText("Gestión de Usuarios");

        searchButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchButton1.setText("Buscar");

        mainPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameLabel1.setText("Nombre: ");

        emaiLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emaiLabel.setText("Email:");

        rolLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rolLabel.setText("ROL:");

        contratoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contratoLabel1.setText("Contraseña:");

        altasTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        altasTitle.setText("Gestión de Altas:");
        altasTitle.setToolTipText("");

        userLlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userLlabel.setText("Lista de usuarios:");

        modButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        modButton.setText("Modificar");
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        altaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        altaLabel.setText("Nombre:");

        nameAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        rLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rLabel.setText("ROL:");

        rolAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        maiLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        maiLabel.setText("EMAIL:");

        mailAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passLabel.setText("Contraseña:");

        passAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        confiLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        confiLabel.setText("Confirmar:");

        confAlta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        altaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        altaButton.setText("ALTA");
        altaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(altaLabel)
                            .addComponent(maiLabel))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mailAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(passLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passAlta)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 102, Short.MAX_VALUE)
                        .addComponent(rLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(confiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confAlta)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(altaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(389, 389, 389))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(altaLabel)
                    .addComponent(nameAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rLabel)
                    .addComponent(rolAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maiLabel)
                    .addComponent(mailAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confiLabel)
                    .addComponent(confAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(altaButton)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(usersTable);

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        idLabel.setText("ID USUARIO:");

        idText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addComponent(contratoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(modButton)
                                .addComponent(altasTitle)
                                .addGroup(mainPanel1Layout.createSequentialGroup()
                                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLabel1)
                                        .addComponent(emaiLabel))
                                    .addGap(31, 31, 31)
                                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                            .addComponent(nameText)
                                            .addGap(18, 18, 18)
                                            .addComponent(rolLabel))
                                        .addComponent(mailText))
                                    .addGap(382, 382, 382)))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLlabel))
                .addContainerGap())
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rolLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nameLabel1)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contratoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(modButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altasTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(userLlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usersPanelLayout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(usersPanelLayout.createSequentialGroup()
                                .addGap(543, 543, 543)
                                .addComponent(ususTitle)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addComponent(ususTitle)
                .addGap(37, 37, 37)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // Obtener valores
        String nombre = nameText.getText().trim();
        String email = mailText.getText().trim();
        String password = ut.hashPass(new String(passText.getPassword()).trim());
        String id = idText.getText().trim();
        Object rolObj = rolCombo.getSelectedItem();

        // Validaciones
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rolObj == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un rol", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El email no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID de usuario no válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ejecutar UPDATE
        ut.ejecutarUpdate(
                utilities.TipoConsulta.UPDATEUSER,
                nombre,
                rolObj.toString(),
                email,
                password,
                id
        );

        JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        cargarDatos();
    }//GEN-LAST:event_modButtonActionPerformed

    private void altaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaButtonActionPerformed
        // Obtener valores
        String nombre = nameAlta.getText().trim();
        String email = mailAlta.getText().trim();

        String password = new String(passAlta.getPassword()).trim();

        // Si confiAlta es JPasswordField, usa esto:
        String confiPass = new String(confAlta.getPassword()).trim();
        // Si confiAlta es JTextField, entonces sería:
        // String confiPass = confiAlta.getText().trim();

        Object rolObj = rolAlta.getSelectedItem();

        // Validaciones
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            nameAlta.requestFocus();
            return;
        }

        if (rolObj == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un rol", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El email no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            mailAlta.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            passAlta.requestFocus();
            return;
        }

        if (confiPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes confirmar la contraseña", "Error", JOptionPane.ERROR_MESSAGE);
            confAlta.requestFocus();
            return;
        }

        if (!password.equals(confiPass)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
            passAlta.requestFocus();
            return;
        }

        ut.ejecutarUpdate(
                utilities.TipoConsulta.ALTA,
                nombre,
                rolObj.toString(),
                email,
                ut.hashPass(password)
        );

        JOptionPane.showMessageDialog(this, "Usuario dado de alta correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCamposMod();
        cargarDatos();
    }//GEN-LAST:event_altaButtonActionPerformed

    private void limpiarCamposMod() {
        nameText.setText("");
        mailText.setText("");
        passText.setText("");
        idText.setText("");
        rolCombo.setSelectedIndex(-1); // nada seleccionado
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaButton;
    private javax.swing.JLabel altaLabel;
    private javax.swing.JLabel altasTitle;
    private javax.swing.JPasswordField confAlta;
    private javax.swing.JLabel confiLabel;
    private javax.swing.JLabel contratoLabel1;
    private javax.swing.JLabel emaiLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maiLabel;
    private javax.swing.JTextField mailAlta;
    private javax.swing.JTextField mailText;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JButton modButton;
    private javax.swing.JTextField nameAlta;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passAlta;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel rLabel;
    private javax.swing.JComboBox<String> rolAlta;
    private javax.swing.JComboBox<String> rolCombo;
    private javax.swing.JLabel rolLabel;
    private javax.swing.JButton searchButton1;
    private javax.swing.JTextField searchField1;
    private javax.swing.JLabel userLlabel;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTable usersTable;
    private javax.swing.JLabel ususTitle;
    // End of variables declaration//GEN-END:variables
}
