/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import com.jmmunoz.netfix.Usuario;
import com.jmmunoz.netfix.utilities;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author juanm
 */
public class UsuariosPanel extends javax.swing.JPanel {

    /**
     * Creates new form incidenciasPanel
     */
    utilities ut = new utilities();
    Usuario usuario;

    public UsuariosPanel(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        cargarDatos();
    }

    public void cargarDatos() {
        idText.setText(usuario.getIdUsuario());
        nameText.setText(usuario.getNombre());
        mailText.setText(usuario.getEmail());

        ResultSet rs = ut.ejecutarConsulta(utilities.TipoConsulta.ROLES, 0);
        rolCombo.removeAllItems();
        try {
            while (rs.next()) {
                rolCombo.addItem(rs.getString("descripcion"));
            }
        } catch (SQLException ex) {
            System.getLogger(SupervisorPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        rolCombo.setSelectedItem(usuario.getRol());
        passText.setText(usuario.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usersPanel = new javax.swing.JPanel();
        ususTitle = new javax.swing.JLabel();
        mainPanel1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        emaiLabel = new javax.swing.JLabel();
        rolLabel = new javax.swing.JLabel();
        contratoLabel1 = new javax.swing.JLabel();
        modButton = new javax.swing.JButton();
        nameText = new javax.swing.JTextField();
        mailText = new javax.swing.JTextField();
        rolCombo = new javax.swing.JComboBox<>();
        passText = new javax.swing.JPasswordField();
        idLabel = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1592, 946));

        usersPanel.setBackground(new java.awt.Color(255, 255, 255));
        usersPanel.setPreferredSize(new java.awt.Dimension(1592, 946));

        ususTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        ususTitle.setText("Gestión de Usuario");

        mainPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nameLabel1.setText("Nombre: ");

        emaiLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        emaiLabel.setText("Email:");

        rolLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rolLabel.setText("ROL:");

        contratoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contratoLabel1.setText("Contraseña:");

        modButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        modButton.setText("Modificar");
        modButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modButtonActionPerformed(evt);
            }
        });

        nameText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        mailText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        rolCombo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        passText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passText.setToolTipText("LA CONTRASEÑA SOLO SE PUEDE CAMBIAR");

        idLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        idLabel.setText("ID USUARIO:");

        idText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout mainPanel1Layout = new javax.swing.GroupLayout(mainPanel1);
        mainPanel1.setLayout(mainPanel1Layout);
        mainPanel1Layout.setHorizontalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addComponent(contratoLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passText, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(rolCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(689, 689, 689))
                    .addGroup(mainPanel1Layout.createSequentialGroup()
                        .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modButton)
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel1)
                                    .addComponent(emaiLabel))
                                .addGap(31, 31, 31)
                                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanel1Layout.createSequentialGroup()
                                        .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rolLabel))
                                    .addComponent(mailText)))
                            .addGroup(mainPanel1Layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanel1Layout.setVerticalGroup(
            mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rolCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rolLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel1)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contratoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modButton)
                .addContainerGap(532, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(ususTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addComponent(ususTitle)
                .addGap(20, 20, 20)
                .addComponent(mainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(usersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modButtonActionPerformed
        // Obtener valores
        String nombre = nameText.getText().trim();
        String email = mailText.getText().trim();
        String password = ut.hashPass(new String(passText.getPassword()).trim());
        String id = idText.getText().trim();
        Object rolObj = rolCombo.getSelectedItem();

        // Validaciones
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rolObj == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un rol", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El email no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID de usuario no válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ejecutar UPDATE
        ut.ejecutarUpdate(
                utilities.TipoConsulta.UPDATEUSER,
                nombre,
                rolObj.toString(),
                email,
                password,
                id
        );

        JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        cargarDatos();
    }//GEN-LAST:event_modButtonActionPerformed

    private void limpiarCamposMod() {
        nameText.setText("");
        mailText.setText("");
        passText.setText("");
        idText.setText("");
        rolCombo.setSelectedIndex(-1); // nada seleccionado
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contratoLabel1;
    private javax.swing.JLabel emaiLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idText;
    private javax.swing.JTextField mailText;
    private javax.swing.JPanel mainPanel1;
    private javax.swing.JButton modButton;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JPasswordField passText;
    private javax.swing.JComboBox<String> rolCombo;
    private javax.swing.JLabel rolLabel;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JLabel ususTitle;
    // End of variables declaration//GEN-END:variables
}
