/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jmmunoz.netfix.vista;

import com.jmmunoz.netfix.modelo.SimuladorDiagnostico;
import com.jmmunoz.netfix.modelo.SimuladorDiagnostico.Aparato;
import com.jmmunoz.netfix.controlador.Utilities;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Juanma Muñoz
 */
/**
 * Panel de Diagnóstico de Aparatos.
 * <p>
 * Permite buscar aparatos por número de teléfono o contrato y realizar
 * diagnósticos en tiempo real utilizando el {@link SimuladorDiagnostico}.
 * Muestra información técnica detallada (MAC, estado, valores ópticos, etc.).
 * </p>
 * 
 * @author Juanma Muñoz
 */
public class AparatosPanel extends javax.swing.JPanel {

        /**
         * Creates new form incidenciasPanel
         */
        Utilities ut;
        SimuladorDiagnostico sd;
        int idAparato;
        String searchText;
        int numConsultas = 0; // Contador de búsquedas/consultas

        public AparatosPanel() {
                initComponents();
                ut = new Utilities();
                sd = new SimuladorDiagnostico();
                com.jmmunoz.netfix.vista.tema.ThemeManager.getInstance().applyAparatosPanelTheme(this);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                apaTitle = new javax.swing.JLabel();
                searchField = new javax.swing.JTextField();
                searchButton = new javax.swing.JButton();
                mainPanel = new javax.swing.JPanel();
                tipLbl = new javax.swing.JLabel();
                macL = new javax.swing.JLabel();
                statusLabel = new javax.swing.JLabel();
                tipoLabel = new javax.swing.JLabel();
                nsLabeel = new javax.swing.JLabel();
                macLabel = new javax.swing.JLabel();
                nombreLabel = new javax.swing.JLabel();
                contratoLabel = new javax.swing.JLabel();
                estadoLabel = new javax.swing.JLabel();
                lasDlabel = new javax.swing.JLabel();
                obserPanel = new javax.swing.JLabel();
                feLastLabel = new javax.swing.JLabel();
                numSLabel = new javax.swing.JLabel();
                obervaText = new javax.swing.JScrollPane();
                observaciones = new javax.swing.JTextArea();
                actualDlbale = new javax.swing.JLabel();
                listaDiag = new javax.swing.JScrollPane();
                actualDiag = new javax.swing.JList<>();
                numConLabel = new javax.swing.JLabel();
                diagnoButton = new javax.swing.JButton();

                apaTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                apaTitle.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.title"));

                searchField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                searchField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchButtonActionPerformed(evt);
                        }
                });

                searchButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                searchButton.setText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.btn.search"));
                searchButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchButtonActionPerformed(evt);
                        }
                });

                mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                tipLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                macL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                statusLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                tipoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                tipoLabel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.label.type"));

                nsLabeel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                nsLabeel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.label.serial"));

                macLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                macLabel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.label.mac"));

                nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                nombreLabel.setText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.label.name"));

                contratoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                contratoLabel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                .getMessage("aparatos.label.contract"));

                estadoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                estadoLabel.setText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.label.status"));

                lasDlabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                lasDlabel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                .getMessage("aparatos.label.last.diag"));

                obserPanel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                obserPanel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                .getMessage("aparatos.label.observations"));

                feLastLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                numSLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                observaciones.setColumns(20);
                observaciones.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                observaciones.setRows(5);
                obervaText.setViewportView(observaciones);

                actualDlbale.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                actualDlbale.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                .getMessage("aparatos.label.current.diag"));

                actualDiag.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                listaDiag.setViewportView(actualDiag);

                numConLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

                javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
                mainPanel.setLayout(mainPanelLayout);
                mainPanelLayout.setHorizontalGroup(
                                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(mainPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(nsLabeel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                .addComponent(numSLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(tipoLabel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                .addComponent(tipLbl,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                137,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(contratoLabel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(numConLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                67,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                false)
                                                                                                                                                .addComponent(nombreLabel)
                                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(estadoLabel)
                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(statusLabel,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addComponent(macLabel)
                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                .addComponent(macL,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                277,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                .addGap(122, 122,
                                                                                                                                                122))
                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(lasDlabel)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(feLastLabel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                243,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)))
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(actualDlbale)
                                                                                                                .addComponent(listaDiag,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                688,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addGroup(mainPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(obserPanel)
                                                                                                                .addComponent(obervaText,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                851,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                mainPanelLayout.setVerticalGroup(
                                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addGroup(mainPanelLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(10, 10, 10)
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(tipoLabel)
                                                                                                                                .addComponent(nombreLabel))
                                                                                                                .addComponent(tipLbl,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                32,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(nsLabeel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(macLabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(macL,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(numSLabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addGroup(mainPanelLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                .addComponent(estadoLabel)
                                                                                                                                .addComponent(contratoLabel)
                                                                                                                                .addComponent(statusLabel,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                32,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(numConLabel,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(mainPanelLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(lasDlabel)
                                                                                                                .addComponent(feLastLabel,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                32,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(137, 137, 137)
                                                                                                .addComponent(obserPanel)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(obervaText,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                311,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                mainPanelLayout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(actualDlbale)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(listaDiag,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                630,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(50, Short.MAX_VALUE)));

                diagnoButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                diagnoButton.setText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("aparatos.btn.execute"));
                diagnoButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                diagnoButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(448, 448, 448)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(searchField,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                417,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(45, 45, 45)
                                                                                                                                .addComponent(searchButton,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                138,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addComponent(apaTitle)))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(537, 537, 537)
                                                                                                .addComponent(diagnoButton,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                396,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(mainPanel,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 19, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(apaTitle)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(searchField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(searchButton,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                32,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(mainPanel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(diagnoButton)
                                                                .addGap(0, 13, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Listener para el buscador.
         * Valida que el campo no esté vacío y ejecuta la carga del diagnóstico.
         * 
         * @param evt Evento del botón.
         */
        private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchButtonActionPerformed
                if (searchField.getText().trim().isEmpty()) {
                        com.jmmunoz.netfix.vista.dialogos.ModernDialog.showMessageDialog(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.error.empty.search"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.title.warning"),
                                        JOptionPane.WARNING_MESSAGE);
                        ut.logAction("WARNING", "AparatosPanel", "Intento de búsqueda con campo vacío.");
                        return; // Detiene la ejecución si está vacío
                }
                searchText = searchField.getText();
                // impresión de depuración eliminada
                cargarDiagnostico();
        }// GEN-LAST:event_searchButtonActionPerformed

        /**
         * Permite realizar una búsqueda programática desde otros paneles.
         * Establece el texto de búsqueda y carga los datos.
         * 
         * @param dato El dato a buscar (MAC, teléfono, contrato).
         */
        public void buscarAparato(String dato) {
                if (dato != null && !dato.trim().isEmpty()) {
                        searchField.setText(dato);
                        searchText = dato;
                        cargarDiagnostico();
                } else {
                        ut.logAction("WARNING", "AparatosPanel", "Intento de búsqueda programática con dato vacío.");
                }
        }

        /**
         * Ejecuta una nueva simulación de diagnóstico para el aparato seleccionado.
         * Utiliza {@link SimuladorDiagnostico} para generar nuevos valores de señal,
         * cobertura y ping, mostrando una animación de carga.
         * 
         * @param evt Evento del botón.
         */
        private void diagnoButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diagnoButtonActionPerformed
                if (numSLabel.getText().trim().isEmpty()) {
                        com.jmmunoz.netfix.vista.dialogos.ModernDialog.showMessageDialog(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.error.no.selection"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.title.warning"),
                                        JOptionPane.WARNING_MESSAGE);
                        ut.logAction("WARNING", "AparatosPanel", "Intento de diagnóstico sin aparato seleccionado.");
                        return; // Detiene la ejecución si está vacío
                }

                // Crear objeto Aparato con los datos ya cargados
                String[] nombreParts = nombreLabel.getText().split(" ", 2); // marca + modelo
                String marca = nombreParts.length > 0 ? nombreParts[0] : "";
                String modelo = nombreParts.length > 1 ? nombreParts[1] : "";

                Aparato a = new Aparato(
                                tipLbl.getText(), // tipo
                                marca, // marca
                                modelo, // modelo
                                numSLabel.getText(), // número de serie
                                macL.getText(), // MAC
                                Integer.parseInt(numConLabel.getText()),
                                idAparato);
                JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

                // Pasamos this::cargarDiagnostico como callback para refrescar datos al
                // terminar
                sd.generarDiagnosticoConCarga(parentFrame, a, actualDiag, this::cargarDiagnostico);

        }// GEN-LAST:event_diagnoButtonActionPerformed

        /**
         * Busca y carga los datos del aparato y su último diagnóstico desde la base de
         * datos.
         * Actualiza todos los labels de información y la lista de valores técnicos.
         */
        public void cargarDiagnostico() {
                try {
                        List<Object[]> resultados = Utilities.buscarDiagnosticoAparato(searchText);

                        for (Object[] fila : resultados) {
                                idAparato = Integer.parseInt(String.valueOf(fila[0]));
                                String tipo = String.valueOf(fila[1]);
                                tipLbl.setText(tipo);

                                // Cambio dinámico de etiqueta N/S por SIM según tipo
                                if ("5G".equalsIgnoreCase(tipo)) {
                                        nsLabeel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.label.sim"));
                                } else {
                                        nsLabeel.setText(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.label.serial"));
                                }

                                nombreLabel.setText(String.valueOf(fila[2]));
                                numSLabel.setText(String.valueOf(fila[3]));
                                macL.setText(String.valueOf(fila[4]));

                                numConLabel.setText(String.valueOf(fila[5]));

                                feLastLabel.setText(String.valueOf(fila[6]));
                                statusLabel.setText(String.valueOf(fila[7]));

                                numConsultas++; // Incrementamos el contador de consultas

                                DefaultListModel<String> model = new DefaultListModel<>();

                                // Si es la primera ejecución (numConsultas == 1), mostramos cabecera
                                if (numConsultas == 1) {
                                        model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.diag.header"));
                                        model.addElement(" ");
                                }

                                model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage(
                                                "aparatos.diag.state") + String.valueOf(fila[7]).toUpperCase());
                                model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                .getMessage("aparatos.diag.speed") + String.valueOf(fila[8]) + " Mbps");

                                if ("FTTH".equalsIgnoreCase(tipo)) {
                                        model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("aparatos.diag.optical") + String.valueOf(fila[9]));
                                } else {
                                        model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage(
                                                        "aparatos.diag.coverage") + String.valueOf(fila[10]));
                                }

                                model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                .getMessage("aparatos.diag.ping") + String.valueOf(fila[11]) + " ms");

                                // Añadir números de teléfono si existen (columna 14)
                                if (fila.length > 14 && fila[14] != null && !String.valueOf(fila[14]).isEmpty()
                                                && !String.valueOf(fila[14]).equals("null")) {
                                        model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage(
                                                        "aparatos.diag.numbers") + String.valueOf(fila[14]));
                                }

                                // Si es la primera ejecución, añadimos las observaciones
                                if (numConsultas == 1) {
                                        model.addElement(" ");
                                        model.addElement(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage(
                                                        "aparatos.diag.observations") + String.valueOf(fila[12]));
                                }

                                actualDiag.setModel(model);
                                observaciones.setText(String.valueOf(fila[12]));
                                ut.logAction("OK", "AparatosPanel",
                                                "Diagnóstico cargado correctamente para ID: " + idAparato);

                        }
                } catch (SQLException ex) {
                        ut.logAction("ERROR", "AparatosPanel", "Error cargando diagnóstico: " + ex.getMessage());
                }
        }

        /**
         * Aplica el tema visual corporativo.
         * Estiliza el panel de búsqueda, el card de detalles y los botones.
         */
        // applyTelecomStyle eliminado - lógica movida a ThemeManager

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JList<String> actualDiag;
        private javax.swing.JLabel actualDlbale;
        private javax.swing.JLabel apaTitle;
        private javax.swing.JLabel contratoLabel;
        private javax.swing.JButton diagnoButton;
        private javax.swing.JLabel estadoLabel;
        private javax.swing.JLabel feLastLabel;
        private javax.swing.JLabel lasDlabel;
        private javax.swing.JScrollPane listaDiag;
        private javax.swing.JLabel macL;
        private javax.swing.JLabel macLabel;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JLabel nombreLabel;
        private javax.swing.JLabel nsLabeel;
        private javax.swing.JLabel numConLabel;
        private javax.swing.JLabel numSLabel;
        private javax.swing.JScrollPane obervaText;
        private javax.swing.JLabel obserPanel;
        private javax.swing.JTextArea observaciones;
        private javax.swing.JButton searchButton;
        private javax.swing.JTextField searchField;
        private javax.swing.JLabel statusLabel;
        private javax.swing.JLabel tipLbl;
        private javax.swing.JLabel tipoLabel;
        // End of variables declaration//GEN-END:variables

        public javax.swing.JLabel getApaTitle() {
                return apaTitle;
        }

        public javax.swing.JTextField getSearchField() {
                return searchField;
        }

        public javax.swing.JButton getSearchButton() {
                return searchButton;
        }

        public javax.swing.JButton getDiagnoButton() {
                return diagnoButton;
        }

        public javax.swing.JPanel getMainPanel() {
                return mainPanel;
        }

        // Muted Labels
        public javax.swing.JLabel getTipoLabel() {
                return tipoLabel;
        }

        public javax.swing.JLabel getNsLabeel() {
                return nsLabeel;
        }

        public javax.swing.JLabel getMacLabel() {
                return macLabel;
        }

        public javax.swing.JLabel getContratoLabel() {
                return contratoLabel;
        }

        public javax.swing.JLabel getEstadoLabel() {
                return estadoLabel;
        }

        public javax.swing.JLabel getLasDlabel() {
                return lasDlabel;
        }

        public javax.swing.JLabel getObserPanel() {
                return obserPanel;
        }

        public javax.swing.JLabel getActualDlbale() {
                return actualDlbale;
        }

        // Value Labels
        public javax.swing.JLabel getTipLbl() {
                return tipLbl;
        }

        public javax.swing.JLabel getNumSLabel() {
                return numSLabel;
        }

        public javax.swing.JLabel getMacL() {
                return macL;
        }

        public javax.swing.JLabel getNumConLabel() {
                return numConLabel;
        }

        public javax.swing.JLabel getStatusLabel() {
                return statusLabel;
        }

        public javax.swing.JLabel getFeLastLabel() {
                return feLastLabel;
        }

        public javax.swing.JLabel getNombreLabel() {
                return nombreLabel;
        }

        // Text Areas / Lists
        public javax.swing.JTextArea getObservaciones() {
                return observaciones;
        }

        public javax.swing.JScrollPane getObervaText() {
                return obervaText;
        }

        public javax.swing.JList<String> getActualDiag() {
                return actualDiag;
        }

        public javax.swing.JScrollPane getListaDiag() {
                return listaDiag;
        }
}
