/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jmmunoz.netfix.vista;

import com.jmmunoz.netfix.modelo.Usuario;
import com.jmmunoz.netfix.controlador.Utilities;
import com.jmmunoz.netfix.vista.tema.ThemeManager;
import com.jmmunoz.netfix.vista.tema.CustomNotification;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Ventana de acceso (Login) de la aplicación.
 * <p>
 * Gestiona la autenticación de usuarios contra la base de datos y la carga
 * del tema visual inicial. Si el acceso es correcto, lanza el
 * {@link MainFrame}.
 * </p>
 * 
 * @author Juanma Muñoz
 */
public class login extends javax.swing.JFrame {

        Utilities ut;

        /**
         * Creates new form login
         */
        public login() {
                initComponents();
                ut = new Utilities();
                ut.seedTestTechnicians();
                ut.initTechnicianSchema(); // Asegurar tablas de técnicos
                if (!java.beans.Beans.isDesignTime()) {
                        ThemeManager.getInstance().applyLoginTheme(this);
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */

        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                password = new javax.swing.JPasswordField();
                mailUser = new javax.swing.JTextField();
                loginButton = new javax.swing.JButton();
                iniciarText = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setResizable(false);

                password.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                password.setToolTipText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("login.tooltip.pass"));

                mailUser.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
                mailUser.setToolTipText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("login.tooltip.user"));

                loginButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                loginButton.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("login.btn.access"));
                loginButton.setToolTipText(
                                com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("login.tooltip.btn"));
                loginButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginButtonActionPerformed(evt);
                        }
                });

                iniciarText.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
                iniciarText.setText(com.jmmunoz.netfix.config.AppConfig.getInstance().getMessage("login.welcome"));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(14, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(iniciarText,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(mailUser,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                594,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(password,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                594,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap())
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(259, 259, 259)
                                                                .addComponent(loginButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                131,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(iniciarText)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(mailUser,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(password,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(loginButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                21,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        /**
         * Maneja la acción de iniciar sesión.
         * Valida credenciales contra la base de datos e inicia la aplicación principal
         * si es correcto.
         * 
         * @param evt Evento de acción.
         */
        private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginButtonActionPerformed

                String email = mailUser.getText().trim();
                String pass = new String(password.getPassword()).trim();

                // 1. Campos vacíos
                if (email.isEmpty() || pass.isEmpty()) {
                        CustomNotification.show(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.empty.title"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.empty.msg"),
                                        CustomNotification.Type.WARNING);
                        ut.logAction("WARNING", "Login", "Intento de login con campos vacíos");
                        return; // No continuar
                }

                // 2. Email no válido
                if (!ut.checkEmail(email)) {
                        CustomNotification.show(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.domain.title"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.domain.msg"),
                                        CustomNotification.Type.WARNING);
                        mailUser.requestFocus();
                        ut.logAction("WARNING", "Login", "Dominio de email inválido: " + email);
                        return; // No continuar
                }

                // 3. Inicio de sesión
                boolean acceso = ut.loggin(email, pass);

                if (!acceso) {
                        CustomNotification.show(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.access.title"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.access.msg"),
                                        CustomNotification.Type.ERROR);
                        ut.logAction("WARNING", "Login", "Credenciales incorrectas para: " + email);
                        return;
                }

                // 4. Acceso correcto: cargar datos del usuario
                try {
                        ResultSet rs = Utilities.ejecutarConsulta(
                                        Utilities.TipoConsulta.USUARIO,
                                        email);

                        if (rs.next()) {

                                Usuario usuario = new Usuario(
                                                rs.getString("id_usuario"),
                                                rs.getString("nombre"),
                                                rs.getString("rol"),
                                                rs.getString("email"),
                                                rs.getString("password"));

                                MainFrame mf = new MainFrame(usuario);
                                mf.setVisible(true);
                                ut.logAction("OK", "Login", "Usuario " + email + " ha iniciado sesión.");
                                this.dispose();
                        }

                } catch (SQLException e) {
                        CustomNotification.show(
                                        this,
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.db.title"),
                                        com.jmmunoz.netfix.config.AppConfig.getInstance()
                                                        .getMessage("login.error.db.msg"),
                                        CustomNotification.Type.ERROR);
                        ut.logAction("ERROR", "Login", "Error SQL durante login: " + e.getMessage());
                }
        }// GEN-LAST:event_loginButtonActionPerformed

        /**
         * Punto de entrada principal de la aplicación.
         * Configura el tema FlatLaf e inicia la ventana de login.
         * 
         * @param args Argumentos de línea de comandos.
         */
        public static void main(String args[]) {

                // Aplicamos el tema a toda la aplicación
                try {
                        ThemeManager.getInstance().setupGlobalTheme(); // una vez
                } catch (Exception ex) {
                        new com.jmmunoz.netfix.controlador.Utilities().logAction("ERROR", "Login.main",
                                        "Error setting theme: " + ex.getMessage());
                }

                // Arranca la pantalla de splash antes de la de login
                java.awt.EventQueue.invokeLater(() -> new SplashScreen().setVisible(true));
        }

        public javax.swing.JTextField getMailUser() {
                return mailUser;
        }

        public javax.swing.JPasswordField getPassword() {
                return password;
        }

        public javax.swing.JButton getLoginButton() {
                return loginButton;
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel iniciarText;
        private javax.swing.JButton loginButton;
        private javax.swing.JTextField mailUser;
        private javax.swing.JPasswordField password;
        // End of variables declaration//GEN-END:variables
}
